#!/bin/bash
#how to install jenkins on a web server
sudo yum install java-1.8.0 -y 
sudo yum remove java-1.7.0-openjdk
sudo yum update -y
sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
sudo yum install jenkins -y
sudo service jenkins start
chkconfig jenkins on

#sudo cat /var/lib/jenkins/secrets/initialAdminPassword
